from __future__ import annotations

import json
import subprocess

from fwrouter_api.core.config import get_settings
from fwrouter_api.services import dataplane_global as dataplane_global_service
from fwrouter_api.services import dnsmasq as dnsmasq_service
from fwrouter_api.services.dataplane_global import build_nft_rule_sets
from fwrouter_api.services.dataplane_nft import render_owned_table_candidate
from fwrouter_api.services.network_contract import (
    lan_interface_allowed,
    local_lan_hosts,
    network_contract_manifest,
)
from fwrouter_api.services.rules_compile import build_effective_rules_artifact


def test_network_contract_drives_protected_dataplane_and_rules(monkeypatch) -> None:
    monkeypatch.setenv(
        "FWROUTER_PROTECTED_IPV4_NETWORKS",
        json.dumps(["127.0.0.0/8", "192.168.1.0/24"]),
    )
    monkeypatch.setenv("FWROUTER_PROTECTED_IPV6_NETWORKS", json.dumps(["::1/128"]))
    monkeypatch.setenv("FWROUTER_RULES_EXTRA_PROTECTED_NETWORKS", json.dumps(["0.0.0.0/8"]))
    monkeypatch.setattr(
        dataplane_global_service,
        "_discover_local_interface_protected_networks",
        lambda: ([], []),
    )
    get_settings.cache_clear()

    nft_sets = build_nft_rule_sets(None)
    rules = build_effective_rules_artifact(
        manual_validation={"rules": []},
        selective_default="direct",
    )
    protected_values = {
        rule["value"]
        for rule in rules["rules"]
        if rule.get("source") == "protected" and rule.get("kind") == "cidr"
    }

    assert "192.168.1.0/24" in nft_sets["protected_ipv4"]
    assert "192.168.0.0/16" not in nft_sets["protected_ipv4"]
    assert "192.168.1.0/24" in protected_values
    assert "192.168.0.0/16" not in protected_values


def test_network_contract_drives_nft_trusted_client_guards(monkeypatch) -> None:
    monkeypatch.setenv("FWROUTER_TRUSTED_CLIENT_IPV4_NETWORKS", json.dumps(["192.168.1.0/24"]))
    monkeypatch.setenv("FWROUTER_TRUSTED_CLIENT_IPV6_NETWORKS", json.dumps(["fd00:1::/64"]))
    get_settings.cache_clear()

    candidate = render_owned_table_candidate(
        {
            "summary": {
                "global_mode": "vpn",
                "selective_default": "direct",
                "requires_vpn_policy_routing": True,
            },
            "global_preflight": {
                "vpn_contour": {
                    "redir_port": 5202,
                    "tproxy_port": 5203,
                    "full_vpn_redir_port": 5204,
                    "full_vpn_tproxy_port": 5205,
                    "fwmark_hex": "0x00000100",
                    "proxy_bypass_mark_hex": "0x00000200",
                    "full_vpn_udp_fwmark_hex": "0x00000102",
                    "full_vpn_tcp_redirect_mark_hex": "0x00000103",
                },
                "profile": {"mihomo": {"contours": {}}},
            },
            "subjects": [],
            "extra": {"rules_effective": {"rules": []}},
        }
    )

    assert "ip saddr { 192.168.1.0/24 }" in candidate
    assert "ip6 saddr { fd00:1::/64 }" in candidate


def test_network_contract_drives_lan_interfaces_and_dnsmasq_hosts(monkeypatch) -> None:
    monkeypatch.setenv("FWROUTER_LAN_INTERFACE_ALLOWLIST", json.dumps(["lan0"]))
    monkeypatch.setenv("FWROUTER_LOCAL_LAN_HOSTS", json.dumps({"router.test": "test UI"}))
    get_settings.cache_clear()

    def fake_run(argv: list[str], check: bool, capture_output: bool, text: bool = False):
        assert argv == ["ip", "-json", "address", "show"]
        payload = [
            {"ifname": "enp2s0", "addr_info": [{"family": "inet", "local": "192.168.0.1"}]},
            {"ifname": "lan0", "addr_info": [{"family": "inet", "local": "192.168.1.1"}]},
            {"ifname": "tailscale0", "addr_info": [{"family": "inet", "local": "100.64.0.1"}]},
        ]
        return subprocess.CompletedProcess(argv, 0, json.dumps(payload), "")

    monkeypatch.setattr(dnsmasq_service.subprocess, "run", fake_run)

    assert lan_interface_allowed("lan0") is True
    assert lan_interface_allowed("enp2s0") is False
    assert dnsmasq_service._discover_router_dns_bindings() == [
        {"ifname": "lan0", "address": "192.168.1.1"}
    ]
    assert dnsmasq_service._build_local_hosts_dnsmasq_text(["192.168.1.1"]).splitlines() == [
        "# Generated by FWRouter v2",
        "# Local LAN ingress hostnames. HTTP Host routing is handled by reverse proxy.",
        "",
        "address=/router.test/192.168.1.1",
    ]
    assert local_lan_hosts() == {"router.test": "test UI"}
    assert network_contract_manifest()["lan_interface_allowlist"] == ["lan0"]
