services:
  fwrouter-xray:
    image: teddysun/xray:latest
    container_name: fwrouter-xray
    restart: unless-stopped
    networks:
      - fwrouter_proxy
    volumes:
      - /var/lib/fwrouter-v2/xray/config.json:/etc/xray/config.json:ro
      - /var/log/fwrouter/xray:/var/log/xray
    expose:
      - "5300"

networks:
  fwrouter_proxy:
    name: ${FWROUTER_DOCKER_PROXY_NETWORK:-fwrouter_proxy}
    external: true
