from __future__ import annotations

import json
import ipaddress
import subprocess
from pathlib import Path
from typing import Any

from fwrouter_api.services.artifacts import atomic_write_text
from fwrouter_api.services.dataplane_global import (
    ANDROID_CONNECTIVITY_DIRECT_DOMAINS,
    _is_android_connectivity_direct_domain,
    _is_protected_service_domain,
    read_effective_rules_artifact,
)
from fwrouter_api.services.dataplane_nft import OWNED_TABLE
from fwrouter_api.services.live_probe_cache import clear_live_probe_cache, get_live_probe_cache


DNSMASQ_RULES_CONF_PATH = Path("/etc/dnsmasq.d/fwrouter-rules.conf")
DNSMASQ_DHCP_DNS_CONF_PATH = Path("/etc/dnsmasq.d/fwrouter-dhcp-dns.conf")
DNSMASQ_IPV6_LAN_CONF_PATH = Path("/etc/dnsmasq.d/fwrouter-ipv6-lan.conf")
DNSMASQ_LOCAL_HOSTS_CONF_PATH = Path("/etc/dnsmasq.d/fwrouter-local-hosts.conf")
DNSMASQ_NFTSET_TABLE = OWNED_TABLE.replace(" ", "#")
DNSMASQ_NFTSET_TABLE_TOKENS = OWNED_TABLE.split()
DNSMASQ_DIRECT_IPV4_SET = "dns_direct_ipv4"
DNSMASQ_VPN_IPV4_SET = "dns_vpn_ipv4"
VIRTUAL_INTERFACE_PREFIXES = ("docker", "br-", "veth", "tailscale", "virbr", "lo")
DNS_CAPTURE_COMMENT = "fwrouter dns capture"
DNSMASQ_ACTIVE_PROBE_SERVER = "127.0.0.1"
DNSMASQ_ACTIVE_PROBE_TIMEOUT_SECONDS = 2
LOCAL_LAN_HOSTS = {
    "fwrouter.lan": "fwrouter UI via local ingress",
    "homes.lan": "Home Assistant via local ingress",
}


def _write_text_if_changed(path: Path, text: str) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == text:
        return False
    atomic_write_text(path, text)
    return True


def _build_local_hosts_dnsmasq_text(router_dns_ipv4: list[str]) -> str:
    lines = [
        "# Generated by FWRouter v2",
        "# Local LAN ingress hostnames. HTTP Host routing is handled by reverse proxy.",
        "",
    ]
    if router_dns_ipv4:
        target = router_dns_ipv4[0]
        for hostname in sorted(LOCAL_LAN_HOSTS):
            lines.append(f"address=/{hostname}/{target}")
    return "\n".join(lines) + "\n"


def _discover_router_dns_bindings() -> list[dict[str, str]]:
    try:
        completed = subprocess.run(
            ["ip", "-json", "address", "show"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return []

    try:
        payload = json.loads(completed.stdout)
    except json.JSONDecodeError:
        return []

    if not isinstance(payload, list):
        return []

    discovered: list[dict[str, str]] = []
    for item in payload:
        if not isinstance(item, dict):
            continue
        ifname = str(item.get("ifname") or "").strip()
        if not ifname or ifname.startswith(VIRTUAL_INTERFACE_PREFIXES):
            continue
        addr_info = item.get("addr_info")
        if not isinstance(addr_info, list):
            continue
        for info in addr_info:
            if not isinstance(info, dict):
                continue
            if str(info.get("family") or "").lower() != "inet":
                continue
            address = str(info.get("local") or "").strip()
            if not address:
                continue
            try:
                parsed = ipaddress.ip_address(address)
            except ValueError:
                continue
            if parsed.version == 4 and parsed.is_private:
                discovered.append({"ifname": ifname, "address": address})

    unique: dict[tuple[str, str], dict[str, str]] = {}
    for binding in discovered:
        unique[(binding["ifname"], binding["address"])] = binding
    return sorted(unique.values(), key=lambda item: (item["ifname"], item["address"]))


def _discover_router_dns_ipv4_addresses() -> list[str]:
    return sorted({binding["address"] for binding in _discover_router_dns_bindings()})


def _discover_router_dns_interfaces() -> list[str]:
    return sorted({binding["ifname"] for binding in _discover_router_dns_bindings()})


def _iptables_rule_present(argv: list[str]) -> bool:
    try:
        completed = subprocess.run(argv, check=False, capture_output=True, text=True)
    except FileNotFoundError:
        return False
    return completed.returncode == 0


def _ensure_iptables_rule(argv_check: list[str], argv_insert: list[str]) -> bool:
    if _iptables_rule_present(argv_check):
        return False
    subprocess.run(argv_insert, check=True, capture_output=True, text=True)
    return True


def _delete_iptables_rule(argv_delete: list[str]) -> bool:
    argv_check = [*argv_delete[:3], "-C", *argv_delete[4:]]
    if not _iptables_rule_present(argv_check):
        return False
    subprocess.run(argv_delete, check=True, capture_output=True, text=True)
    return True


def inspect_dns_capture_status() -> dict[str, Any]:
    bindings = _discover_router_dns_bindings()
    if not bindings:
        return {
            "ok": False,
            "interfaces": [],
            "bindings": [],
            "rules_present": [],
            "missing": ["router_dns_interfaces_missing"],
        }

    missing: list[str] = []
    rules_present: list[dict[str, Any]] = []
    for binding in bindings:
        ifname = binding["ifname"]
        address = binding["address"]
        udp_check = [
            "iptables",
            "-t",
            "nat",
            "-C",
            "PREROUTING",
            "-i",
            ifname,
            "-p",
            "udp",
            "--dport",
            "53",
            "-m",
            "comment",
            "--comment",
            DNS_CAPTURE_COMMENT,
            "-j",
            "DNAT",
            "--to-destination",
            f"{address}:53",
        ]
        tcp_check = [
            "iptables",
            "-t",
            "nat",
            "-C",
            "PREROUTING",
            "-i",
            ifname,
            "-p",
            "tcp",
            "--dport",
            "53",
            "-m",
            "comment",
            "--comment",
            DNS_CAPTURE_COMMENT,
            "-j",
            "DNAT",
            "--to-destination",
            f"{address}:53",
        ]
        udp_present = _iptables_rule_present(udp_check)
        tcp_present = _iptables_rule_present(tcp_check)
        rules_present.append(
            {
                "ifname": ifname,
                "address": address,
                "udp": udp_present,
                "tcp": tcp_present,
            }
        )
        if not udp_present:
            missing.append(f"dns_capture_udp_missing:{ifname}:{address}")
        if not tcp_present:
            missing.append(f"dns_capture_tcp_missing:{ifname}:{address}")

    return {
        "ok": not missing,
        "interfaces": sorted({binding["ifname"] for binding in bindings}),
        "bindings": bindings,
        "rules_present": rules_present,
        "missing": missing,
    }


def ensure_dns_capture_rules() -> dict[str, Any]:
    bindings = _discover_router_dns_bindings()
    inserted: list[dict[str, Any]] = []
    errors: list[str] = []

    for binding in bindings:
        ifname = binding["ifname"]
        address = binding["address"]
        udp_check = [
            "iptables", "-t", "nat", "-C", "PREROUTING",
            "-i", ifname, "-p", "udp", "--dport", "53",
            "-m", "comment", "--comment", DNS_CAPTURE_COMMENT,
            "-j", "DNAT", "--to-destination", f"{address}:53",
        ]
        udp_insert = [
            "iptables", "-t", "nat", "-I", "PREROUTING", "1",
            "-i", ifname, "-p", "udp", "--dport", "53",
            "-m", "comment", "--comment", DNS_CAPTURE_COMMENT,
            "-j", "DNAT", "--to-destination", f"{address}:53",
        ]
        tcp_check = [
            "iptables", "-t", "nat", "-C", "PREROUTING",
            "-i", ifname, "-p", "tcp", "--dport", "53",
            "-m", "comment", "--comment", DNS_CAPTURE_COMMENT,
            "-j", "DNAT", "--to-destination", f"{address}:53",
        ]
        tcp_insert = [
            "iptables", "-t", "nat", "-I", "PREROUTING", "1",
            "-i", ifname, "-p", "tcp", "--dport", "53",
            "-m", "comment", "--comment", DNS_CAPTURE_COMMENT,
            "-j", "DNAT", "--to-destination", f"{address}:53",
        ]
        try:
            legacy_udp_delete = [
                "iptables", "-t", "nat", "-D", "PREROUTING",
                "-i", ifname, "-p", "udp", "--dport", "53",
                "-m", "comment", "--comment", DNS_CAPTURE_COMMENT,
                "-j", "REDIRECT", "--to-ports", "53",
            ]
            legacy_tcp_delete = [
                "iptables", "-t", "nat", "-D", "PREROUTING",
                "-i", ifname, "-p", "tcp", "--dport", "53",
                "-m", "comment", "--comment", DNS_CAPTURE_COMMENT,
                "-j", "REDIRECT", "--to-ports", "53",
            ]
            _delete_iptables_rule(legacy_udp_delete)
            _delete_iptables_rule(legacy_tcp_delete)
            udp_changed = _ensure_iptables_rule(udp_check, udp_insert)
            tcp_changed = _ensure_iptables_rule(tcp_check, tcp_insert)
        except (FileNotFoundError, subprocess.CalledProcessError) as exc:
            errors.append(f"{ifname}:{address}:{exc}")
            continue
        inserted.append({"ifname": ifname, "address": address, "udp_changed": udp_changed, "tcp_changed": tcp_changed})

    status = inspect_dns_capture_status()
    return {
        "ok": not errors and bool(status.get("ok")),
        "interfaces": sorted({binding["ifname"] for binding in bindings}),
        "bindings": bindings,
        "inserted": inserted,
        "errors": errors,
        "status": status,
    }


def _iter_dnsmasq_probe_targets(rules: list[Any]) -> list[dict[str, str]]:
    targets: list[dict[str, str]] = []
    seen_actions: set[str] = set()
    for rule in rules:
        if not isinstance(rule, dict):
            continue
        kind = str(rule.get("kind") or "").lower()
        if kind not in {"domain", "domain_suffix"}:
            continue
        action = str(rule.get("action") or "").upper()
        if action not in {"VPN", "DIRECT"} or action in seen_actions:
            continue
        value = str(rule.get("value") or "").strip().lower().strip(".")
        if not value:
            continue
        try:
            value = value.encode("idna").decode("ascii")
        except Exception:
            continue
        if _is_protected_service_domain(value):
            continue
        seen_actions.add(action)
        targets.append(
            {
                "action": action,
                "domain": value,
                "set_name": DNSMASQ_VPN_IPV4_SET if action == "VPN" else DNSMASQ_DIRECT_IPV4_SET,
            }
        )
        if len(seen_actions) == 2:
            break
    return targets


def _resolve_ipv4_via_local_dnsmasq(domain: str) -> list[str]:
    try:
        completed = subprocess.run(
            [
                "dig",
                f"@{DNSMASQ_ACTIVE_PROBE_SERVER}",
                domain,
                "A",
                "+short",
                f"+time={DNSMASQ_ACTIVE_PROBE_TIMEOUT_SECONDS}",
                "+tries=1",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return []

    addresses: list[str] = []
    for line in completed.stdout.splitlines():
        value = line.strip()
        if not value:
            continue
        try:
            parsed = ipaddress.ip_address(value)
        except ValueError:
            continue
        if parsed.version == 4:
            addresses.append(value)
    return addresses


def _nft_set_contains_ipv4(set_name: str, address: str) -> bool:
    try:
        completed = subprocess.run(
            [
                "nft",
                "get",
                "element",
                *DNSMASQ_NFTSET_TABLE_TOKENS,
                set_name,
                "{",
                address,
                "}",
            ],
            check=False,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return False
    return completed.returncode == 0


def _probe_dnsmasq_nftset_materialization() -> dict[str, Any]:
    artifact = read_effective_rules_artifact()
    rules = artifact.get("rules", []) if isinstance(artifact, dict) else []
    targets = _iter_dnsmasq_probe_targets(rules if isinstance(rules, list) else [])
    if not targets:
        return {
            "ok": True,
            "probes": [],
            "missing": [],
            "probe_count": 0,
            "restart_recommended": False,
            "status": "not_applicable",
        }

    probes: list[dict[str, Any]] = []
    missing: list[str] = []

    for target in targets:
        resolved_ipv4 = _resolve_ipv4_via_local_dnsmasq(target["domain"])
        probe: dict[str, Any] = {
            "action": target["action"],
            "domain": target["domain"],
            "set_name": target["set_name"],
            "resolved_ipv4": resolved_ipv4,
            "materialized": [],
        }
        if not resolved_ipv4:
            probe["ok"] = False
            probe["error_code"] = "dnsmasq_probe_resolve_failed"
            missing.append(f"dnsmasq_nftset_probe_resolve_failed:{target['action'].lower()}:{target['domain']}")
            probes.append(probe)
            continue

        not_materialized = [address for address in resolved_ipv4 if not _nft_set_contains_ipv4(target["set_name"], address)]
        probe["materialized"] = [address for address in resolved_ipv4 if address not in not_materialized]
        if not_materialized:
            probe["ok"] = False
            probe["error_code"] = "dnsmasq_probe_materialization_missing"
            probe["missing_ipv4"] = not_materialized
            for address in not_materialized:
                missing.append(
                    "dnsmasq_nftset_probe_materialization_missing:"
                    f"{target['action'].lower()}:{target['domain']}:{address}"
                )
        else:
            probe["ok"] = True
            probe["error_code"] = None
        probes.append(probe)

    return {
        "ok": not missing,
        "probes": probes,
        "missing": missing,
        "probe_count": len(probes),
        "restart_recommended": bool(missing),
        "status": "ok" if not missing else "unhealthy",
    }


def _inspect_dnsmasq_selective_status_uncached() -> dict[str, Any]:
    router_dns_ipv4 = _discover_router_dns_ipv4_addresses()
    router_dns_interfaces = _discover_router_dns_interfaces()
    rules_conf_exists = DNSMASQ_RULES_CONF_PATH.exists()
    dhcp_dns_conf_exists = DNSMASQ_DHCP_DNS_CONF_PATH.exists()
    ipv6_lan_conf_exists = DNSMASQ_IPV6_LAN_CONF_PATH.exists()
    local_hosts_conf_exists = DNSMASQ_LOCAL_HOSTS_CONF_PATH.exists()
    dhcp_dns_text = (
        DNSMASQ_DHCP_DNS_CONF_PATH.read_text(encoding="utf-8")
        if dhcp_dns_conf_exists
        else ""
    )
    ipv6_lan_text = (
        DNSMASQ_IPV6_LAN_CONF_PATH.read_text(encoding="utf-8")
        if ipv6_lan_conf_exists
        else ""
    )
    forced_dns_configured = bool(router_dns_ipv4) and all(
        address in dhcp_dns_text for address in router_dns_ipv4
    )
    ipv6_filter_configured = "filter-AAAA" in ipv6_lan_text
    dns_capture_status = inspect_dns_capture_status()
    nftset_probe_status = _probe_dnsmasq_nftset_materialization()
    missing = [
        *([] if router_dns_ipv4 else ["router_dns_ipv4_missing"]),
        *([] if router_dns_interfaces else ["router_dns_interfaces_missing"]),
        *([] if rules_conf_exists else ["rules_conf_missing"]),
        *([] if dhcp_dns_conf_exists else ["dhcp_dns_conf_missing"]),
        *([] if ipv6_lan_conf_exists else ["ipv6_lan_conf_missing"]),
        *([] if local_hosts_conf_exists else ["local_hosts_conf_missing"]),
        *([] if forced_dns_configured or not router_dns_ipv4 else ["dhcp_dns_force_mismatch"]),
        *([] if ipv6_filter_configured else ["ipv6_filter_aaaa_missing"]),
        *(dns_capture_status.get("missing") or []),
        *(nftset_probe_status.get("missing") or []),
    ]
    return {
        "ok": not missing,
        "router_dns_ipv4": router_dns_ipv4,
        "router_dns_interfaces": router_dns_interfaces,
        "rules_conf_path": str(DNSMASQ_RULES_CONF_PATH),
        "rules_conf_exists": rules_conf_exists,
        "dhcp_dns_conf_path": str(DNSMASQ_DHCP_DNS_CONF_PATH),
        "dhcp_dns_conf_exists": dhcp_dns_conf_exists,
        "ipv6_lan_conf_path": str(DNSMASQ_IPV6_LAN_CONF_PATH),
        "ipv6_lan_conf_exists": ipv6_lan_conf_exists,
        "local_hosts_conf_path": str(DNSMASQ_LOCAL_HOSTS_CONF_PATH),
        "local_hosts_conf_exists": local_hosts_conf_exists,
        "forced_dns_configured": forced_dns_configured,
        "ipv6_filter_configured": ipv6_filter_configured,
        "dns_capture_status": dns_capture_status,
        "nftset_probe_status": nftset_probe_status,
        "missing": missing,
    }


def inspect_dnsmasq_selective_status() -> dict[str, Any]:
    return get_live_probe_cache(
        "dnsmasq.selective_status",
        ttl_seconds=2.0,
        loader=_inspect_dnsmasq_selective_status_uncached,
    )


def reconcile_dnsmasq_rules() -> dict[str, Any]:
    """Generate dnsmasq rules from effective rules and restart dnsmasq."""

    artifact = read_effective_rules_artifact()
    if artifact is None:
        return {"ok": True, "message": "No effective rules artifact found; skipping dnsmasq reconcile."}

    rules = artifact.get("rules", [])
    lines = [
        "# Generated by FWRouter v2",
        "# Decision logic is in the core; dnsmasq populates nft sets and applies DNS upstream overrides.",
        "",
    ]

    vpn_dns_forward_count = 0
    direct_domain_count = 0
    nftset_rule_count = 0

    for domain in ANDROID_CONNECTIVITY_DIRECT_DOMAINS:
        lines.append(f"nftset=/{domain}/4#{DNSMASQ_NFTSET_TABLE}#{DNSMASQ_DIRECT_IPV4_SET}")
        direct_domain_count += 1
        nftset_rule_count += 1

    for rule in rules:
        if not isinstance(rule, dict):
            continue
        kind = str(rule.get("kind") or "").lower()
        if kind not in {"domain", "domain_suffix"}:
            continue

        value = str(rule.get("value") or "").strip().lower().strip(".")
        if not value:
            continue

        try:
            value = value.encode("idna").decode("ascii")
        except Exception:
            continue

        if _is_protected_service_domain(value):
            continue
        if _is_android_connectivity_direct_domain(value):
            continue
            
        action = str(rule.get("action") or "").upper()
        
        if action == "VPN":
            lines.append(f"server=/{value}/1.1.1.1")
            lines.append(f"nftset=/{value}/4#{DNSMASQ_NFTSET_TABLE}#{DNSMASQ_VPN_IPV4_SET}")
            vpn_dns_forward_count += 1
            nftset_rule_count += 1
        elif action == "DIRECT":
            lines.append(f"nftset=/{value}/4#{DNSMASQ_NFTSET_TABLE}#{DNSMASQ_DIRECT_IPV4_SET}")
            direct_domain_count += 1
            nftset_rule_count += 1

    rules_text = "\n".join(lines) + "\n"
    router_dns_ipv4 = _discover_router_dns_ipv4_addresses()
    dhcp_dns_lines = [
        "# Generated by FWRouter v2",
        "# Force LAN clients to use router DNS so domain-aware selective nft sets materialize.",
        "",
    ]
    if router_dns_ipv4:
        dhcp_dns_lines.append(
            "dhcp-option-force=option:dns-server," + ",".join(router_dns_ipv4)
        )
    dhcp_dns_text = "\n".join(dhcp_dns_lines) + "\n"
    ipv6_lan_text = "\n".join(
        [
            "# Generated by FWRouter v2",
            "# LAN clients must stay IPv4-only; do not hand AAAA answers to local DNS clients.",
            "",
            "filter-AAAA",
        ]
    ) + "\n"
    local_hosts_text = _build_local_hosts_dnsmasq_text(router_dns_ipv4)
    rules_changed = _write_text_if_changed(DNSMASQ_RULES_CONF_PATH, rules_text)
    dhcp_dns_changed = _write_text_if_changed(DNSMASQ_DHCP_DNS_CONF_PATH, dhcp_dns_text)
    ipv6_lan_changed = _write_text_if_changed(DNSMASQ_IPV6_LAN_CONF_PATH, ipv6_lan_text)
    local_hosts_changed = _write_text_if_changed(DNSMASQ_LOCAL_HOSTS_CONF_PATH, local_hosts_text)
    changed = rules_changed or dhcp_dns_changed or ipv6_lan_changed or local_hosts_changed

    try:
        dns_capture = ensure_dns_capture_rules()
        if not dns_capture["ok"]:
            return {
                "ok": False,
                "error_code": "DNSMASQ_DNS_CAPTURE_FAILED",
                "message": "Failed to enforce LAN DNS capture rules.",
                "router_dns_ipv4": router_dns_ipv4,
                "dns_capture": dns_capture,
            }
        restart_reason = "config_changed" if changed else None
        if changed:
            subprocess.run(["systemctl", "restart", "dnsmasq"], check=True, capture_output=True)
            clear_live_probe_cache()
        selective_status = inspect_dnsmasq_selective_status()
        nftset_probe_status = selective_status.get("nftset_probe_status")
        if (
            not changed
            and isinstance(nftset_probe_status, dict)
            and not bool(nftset_probe_status.get("ok"))
            and bool(nftset_probe_status.get("restart_recommended"))
        ):
            subprocess.run(["systemctl", "restart", "dnsmasq"], check=True, capture_output=True)
            clear_live_probe_cache()
            selective_status = inspect_dnsmasq_selective_status()
            restart_reason = "nftset_probe_unhealthy"
        return {
            "ok": bool(selective_status["ok"]),
            "vpn_dns_forward_count": vpn_dns_forward_count,
            "direct_domain_count": direct_domain_count,
            "nftset_rule_count": nftset_rule_count,
            "rules_changed": rules_changed,
            "dhcp_dns_changed": dhcp_dns_changed,
            "ipv6_lan_changed": ipv6_lan_changed,
            "local_hosts_changed": local_hosts_changed,
            "restart_required": bool(restart_reason),
            "restart_reason": restart_reason,
            "router_dns_ipv4": router_dns_ipv4,
            "dns_capture": dns_capture,
            "selective_status": selective_status,
            "error_code": None if selective_status["ok"] else "DNSMASQ_SELECTIVE_CONTRACT_INCOMPLETE",
            "message": (
                "Dnsmasq rules reconciled: "
                f"{vpn_dns_forward_count} VPN domain forwarders, "
                f"{direct_domain_count} DIRECT domains, "
                f"{nftset_rule_count} nftset bindings."
            ),
        }
    except subprocess.CalledProcessError as exc:
        return {
            "ok": False,
            "error_code": "DNSMASQ_RESTART_FAILED",
            "message": "Failed to restart dnsmasq service.",
            "stderr": exc.stderr.decode("utf-8") if exc.stderr else "",
        }
