services:
  mihomo2:
    image: metacubex/mihomo:v1.19.19
    container_name: fwrouter-mihomo-2
    restart: unless-stopped

    network_mode: host

    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

    volumes:
      - /etc/fwrouter/mihomo2/config.yaml:/root/.config/mihomo/config.yaml:ro
      - /var/lib/fwrouter/mihomo2/state:/root/.config/mihomo
      - /var/lib/fwrouter/mihomo2:/root/.config/mihomo/providers

    environment:
      - TZ=Europe/Amsterdam
